import fs from 'node:fs';
const timing=JSON.parse(fs.readFileSync('timing.json','utf8'));
const data=JSON.stringify(timing);
const html=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>BCD Decoder — Educational Video</title><style>
@font-face{font-family:'Teaching Sans';src:url('assets/teaching-sans.ttf')}@font-face{font-family:'Teaching Mono';src:url('assets/teaching-mono.ttf')}
*{box-sizing:border-box}html,body{margin:0;background:#070e19;color:#edf4fc;font-family:'Teaching Sans',sans-serif}body{display:flex;flex-direction:column;align-items:center;padding:20px;min-height:100vh}.viewer{width:min(100%,1440px)}#viewport{width:100%;aspect-ratio:16/9;position:relative;overflow:hidden;background:#091321;box-shadow:0 12px 70px #0006;border:1px solid #33495e}#stage{width:1920px;height:1080px;position:absolute;left:0;top:0;transform-origin:0 0;background:#091321}.kicker{position:absolute;left:64px;top:43px;font-size:23px;letter-spacing:2px;color:#77edcc}.number{position:absolute;right:64px;top:43px;font-size:23px;color:#a8b9cd}h1{position:absolute;left:64px;top:91px;margin:0;font-size:60px;font-weight:400;letter-spacing:-1.5px;max-width:1780px}#diagram{position:absolute;left:64px;top:208px;width:1792px;height:640px}#takeaway{position:absolute;left:64px;right:64px;top:869px;border-top:1px solid #33495e;padding-top:19px;font-size:30px;margin:0}#caption{position:absolute;left:140px;right:140px;top:950px;min-height:82px;display:flex;align-items:center;justify-content:center;text-align:center;font-size:29px;line-height:1.32;padding:8px 28px;background:#152438;border-radius:10px}#progress{position:absolute;left:64px;top:188px;width:1792px;height:3px;background:#77edcc;transform-origin:left center}.controls{display:flex;justify-content:center;margin:18px 0}audio{width:min(960px,94%)}
</style></head><body><main class="viewer"><div id="viewport"><div id="stage"><div id="chapter" class="kicker"></div><div id="number" class="number"></div><h1 id="title"></h1><canvas id="diagram" width="1792" height="640"></canvas><p id="takeaway"></p><div id="caption"></div><div id="progress"></div></div></div><div class="controls"><audio id="audio" controls preload="metadata" src="assets/voice.mp3"></audio></div></main><script src="logic.js"></script><script src="visuals.js"></script><script>
const DATA=${data};const audio=document.getElementById('audio'),canvas=document.getElementById('diagram'),context=canvas.getContext('2d');
let current=-1;window.renderAt=function(time){const t=Math.min(DATA.duration-.001,Math.max(0,time));let i=DATA.scenes.findIndex(s=>t>=s.start&&t<s.start+s.duration);if(i<0)i=DATA.scenes.length-1;const s=DATA.scenes[i],local=t-s.start;if(i!==current){document.getElementById('chapter').textContent=s.chapter;document.getElementById('number').textContent=String(i+1).padStart(2,'0')+' / 15';document.getElementById('title').textContent=s.title;document.getElementById('takeaway').textContent=s.takeaway;current=i;}const violations=BCDRender.paint(context,i,local,s.duration,s);const c=DATA.captions.find(c=>t>=c.start&&t<c.end);document.getElementById('caption').textContent=c?c.text:'';document.getElementById('caption').style.opacity=c?'1':'0';document.getElementById('progress').style.transform='scaleX('+local/s.duration+')';return {index:i,local,violations};};
function resize(){document.getElementById('stage').style.transform='scale('+document.getElementById('viewport').clientWidth/1920+')';}new ResizeObserver(resize).observe(document.getElementById('viewport'));resize();
function frame(){renderAt(audio.currentTime);if(!audio.paused)requestAnimationFrame(frame);}audio.addEventListener('play',frame);audio.addEventListener('pause',()=>renderAt(audio.currentTime));audio.addEventListener('seeked',()=>renderAt(audio.currentTime));audio.addEventListener('timeupdate',()=>{if(!audio.paused)renderAt(audio.currentTime);});document.addEventListener('keydown',e=>{if(e.code==='Space'){e.preventDefault();audio.paused?audio.play():audio.pause();}if(e.code==='ArrowRight')audio.currentTime=Math.min(DATA.duration,audio.currentTime+5);if(e.code==='ArrowLeft')audio.currentTime=Math.max(0,audio.currentTime-5);});
window.BCDTiming=DATA;document.fonts.ready.then(()=>renderAt(0));renderAt(0);
</script></body></html>`;
fs.writeFileSync('player.html',html);
console.log('Wrote standalone player.html (video + centered audio controls).');
